import { SavedStudy } from '@/types/study';

export function exportToText(study: SavedStudy): void {
  const { scripture, result, savedAt } = study;
  const date = new Date(savedAt).toLocaleString();

  const lines: string[] = [
    '═══════════════════════════════════════════════',
    '                  DIVIDING',
    '         AI-Powered Bible Study Report',
    '═══════════════════════════════════════════════',
    '',
    `Date: ${date}`,
    '',
    '── SCRIPTURE ──────────────────────────────────',
    scripture,
    '',
    '── OVERVIEW ───────────────────────────────────',
    result.overview,
    '',
    '── CROSS REFERENCES ───────────────────────────',
    ...(result.crossReferences.length
      ? result.crossReferences.map(
          (cr) => `• ${cr.reference}: ${cr.text}\n  → ${cr.connection}`
        )
      : ['No cross references found.']),
    '',
    '── GREEK/HEBREW WORDS ─────────────────────────',
    ...(result.greekWords.length
      ? result.greekWords.map(
          (gw) =>
            `• ${gw.word} (${gw.transliteration})${gw.englishWord ? ' · "' + gw.englishWord + '"' : ''}${gw.strongsNumber ? ' [' + gw.strongsNumber + ']' : ''}\n  Definition: ${gw.definition}${gw.usage ? '\n  Usage: ' + gw.usage : ''}`
        )
      : ['No Greek/Hebrew word analysis.']),
    '',
    '── HISTORICAL & CULTURAL CONTEXT ──────────────',
    result.historicalContext,
    '',
    '── COMMENTARIES ───────────────────────────────',
    ...(result.commentaries.length
      ? result.commentaries.map(
          (c) => `• ${c.author} (${c.source}):\n  "${c.text}"`
        )
      : ['No commentaries available.']),
    '',
    '═══════════════════════════════════════════════',
    '   Generated by Dividing — dividing.app',
    '═══════════════════════════════════════════════',
  ];

  const content = lines.join('\n');
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `dividing-study-${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export async function exportToPDF(study: SavedStudy): Promise<void> {
  // Dynamic import to avoid SSR issues
  const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
    import('jspdf'),
    import('html2canvas'),
  ]);

  // Build a temporary off-screen element
  const el = document.createElement('div');
  el.style.cssText = `
    position: fixed; left: -9999px; top: 0;
    width: 794px; padding: 48px;
    font-family: Georgia, serif;
    background: #ffffff; color: #1a1a2e;
    line-height: 1.7;
  `;

  const { scripture, result, savedAt } = study;
  const date = new Date(savedAt).toLocaleString();

  el.innerHTML = `
    <div style="text-align:center;margin-bottom:32px;">
      <div style="font-size:28px;font-weight:800;letter-spacing:0.15em;color:#18181b;">DIVIDING</div>
      <div style="font-size:13px;color:#666;margin-top:4px;">AI-Powered Bible Study Report • ${date}</div>
      <div style="width:60px;height:3px;background:#18181b;margin:16px auto 0;border-radius:2px;"></div>
    </div>

    <div style="background:#f4f4f5;border-left:4px solid #18181b;padding:20px 24px;border-radius:8px;margin-bottom:28px;">
      <div style="font-size:11px;text-transform:uppercase;letter-spacing:0.1em;color:#18181b;font-weight:700;margin-bottom:8px;">Scripture</div>
      <div style="font-size:15px;font-style:italic;color:#1a1a2e;">${scripture}</div>
    </div>

    <div style="margin-bottom:24px;">
      <div style="font-size:13px;text-transform:uppercase;letter-spacing:0.1em;color:#18181b;font-weight:700;margin-bottom:10px;border-bottom:1px solid #e5e7eb;padding-bottom:6px;">Overview</div>
      <div style="font-size:14px;color:#374151;">${result.overview}</div>
    </div>

    ${result.crossReferences.length ? `
    <div style="margin-bottom:24px;">
      <div style="font-size:13px;text-transform:uppercase;letter-spacing:0.1em;color:#18181b;font-weight:700;margin-bottom:10px;border-bottom:1px solid #e5e7eb;padding-bottom:6px;">Cross References</div>
      ${result.crossReferences.map((cr) => `
        <div style="margin-bottom:12px;padding:12px;background:#f9fafb;border-radius:6px;">
          <div style="font-weight:700;font-size:14px;color:#1a1a2e;">${cr.reference}</div>
          <div style="font-style:italic;color:#6b7280;font-size:13px;margin:4px 0;">"${cr.text}"</div>
          <div style="font-size:13px;color:#374151;">${cr.connection}</div>
        </div>
      `).join('')}
    </div>` : ''}

    ${result.greekWords.length ? `
    <div style="margin-bottom:24px;">
      <div style="font-size:13px;text-transform:uppercase;letter-spacing:0.1em;color:#18181b;font-weight:700;margin-bottom:10px;border-bottom:1px solid #e5e7eb;padding-bottom:6px;">Greek/Hebrew Words</div>
      ${result.greekWords.map((gw) => `
        <div style="margin-bottom:12px;padding:12px;background:#f9fafb;border-radius:6px;">
          <span style="font-size:16px;font-weight:700;color:#18181b;">${gw.word}</span>
          <span style="color:#6b7280;font-size:13px;margin-left:8px;">(${gw.transliteration})${gw.englishWord ? ' · "' + gw.englishWord + '"' : ''}${gw.strongsNumber ? ' · ' + gw.strongsNumber : ''}</span>
          <div style="font-size:13px;color:#374151;margin-top:4px;">${gw.definition}</div>
          ${gw.usage ? `<div style="font-size:12px;color:#6b7280;margin-top:4px;font-style:italic;">${gw.usage}</div>` : ''}
        </div>
      `).join('')}
    </div>` : ''}

    <div style="margin-bottom:24px;">
      <div style="font-size:13px;text-transform:uppercase;letter-spacing:0.1em;color:#18181b;font-weight:700;margin-bottom:10px;border-bottom:1px solid #e5e7eb;padding-bottom:6px;">Historical & Cultural Context</div>
      <div style="font-size:14px;color:#374151;">${result.historicalContext}</div>
    </div>

    ${result.commentaries.length ? `
    <div style="margin-bottom:24px;">
      <div style="font-size:13px;text-transform:uppercase;letter-spacing:0.1em;color:#18181b;font-weight:700;margin-bottom:10px;border-bottom:1px solid #e5e7eb;padding-bottom:6px;">Commentaries</div>
      ${result.commentaries.map((c) => `
        <div style="margin-bottom:12px;padding:12px;background:#f9fafb;border-radius:6px;border-left:3px solid #27272a;">
          <div style="font-size:12px;font-weight:700;color:#27272a;margin-bottom:6px;">${c.author} · ${c.source}</div>
          <div style="font-size:13px;font-style:italic;color:#374151;">"${c.text}"</div>
        </div>
      `).join('')}
    </div>` : ''}

    <div style="text-align:center;margin-top:32px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:11px;color:#9ca3af;">
      Generated by Dividing · dividing.app
    </div>
  `;

  document.body.appendChild(el);

  try {
    const canvas = await html2canvas(el, { scale: 1.5, useCORS: true, backgroundColor: '#ffffff' });
    const imgData = canvas.toDataURL('image/jpeg', 0.8);
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'px', format: 'a4', compress: true });
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

    let yOffset = 0;
    const pageHeight = pdf.internal.pageSize.getHeight();

    while (yOffset < pdfHeight) {
      if (yOffset > 0) pdf.addPage();
      pdf.addImage(imgData, 'JPEG', 0, -yOffset, pdfWidth, pdfHeight, undefined, 'FAST');
      yOffset += pageHeight;
    }

    pdf.save(`dividing-study-${Date.now()}.pdf`);
  } finally {
    document.body.removeChild(el);
  }
}
